# Generated by Django 2.0.2 on 2018-02-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_mezzi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mezzo',
            fields=[
                ('idMezzo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('GC', 'Golf-Car'), ('CE', 'Carrello-Elevatore'), ('CS', 'Carrello-Stoccatore'), ('T', 'Trattore')], max_length=15)),
                ('modello', models.CharField(blank=True, max_length=100, null=True)),
                ('matricola', models.CharField(blank=True, max_length=100, null=True)),
                ('matricola_fornitore', models.CharField(blank=True, max_length=100, null=True)),
                ('descrizione', models.CharField(blank=True, max_length=100, null=True)),
                ('colore', models.CharField(blank=True, max_length=100, null=True)),
                ('prezzo_acq', models.CharField(blank=True, max_length=30, null=True)),
                ('canonoe_noleggio_fornitore', models.CharField(blank=True, max_length=30, null=True)),
                ('canonoe_noleggio_ferlog', models.CharField(blank=True, max_length=30, null=True)),
                ('canonoe_noleggio_cliente', models.CharField(blank=True, max_length=30, null=True)),
                ('inizio_noleggio', models.DateField(blank=True, null=True)),
                ('fine_noleggio', models.DateField(blank=True, null=True)),
                ('durata_noleggio', models.CharField(blank=True, max_length=30, null=True)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('immagine', models.ImageField(upload_to='staticimage/profile')),
                ('cliente', models.ForeignKey(blank=True, on_delete=None, to='gest_mezzi.Cliente')),
                ('fornitore', models.ForeignKey(blank=True, on_delete=None, to='gest_mezzi.Fornitore')),
            ],
            options={
                'verbose_name_plural': 'Mezzi',
            },
        ),
    ]
