# Generated by Django 2.0.2 on 2018-02-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_mezzi', '0002_mezzo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impianto',
            fields=[
                ('idImpianto', models.AutoField(primary_key=True, serialize=False)),
                ('denominazione', models.CharField(blank=True, max_length=100, null=True)),
                ('indirizzo', models.CharField(blank=True, max_length=100, null=True)),
                ('citta', models.CharField(max_length=50)),
                ('telefono_rif', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Impianti',
            },
        ),
        migrations.AddField(
            model_name='mezzo',
            name='ubicazione',
            field=models.ManyToManyField(to='gest_mezzi.Impianto'),
        ),
    ]
