# Generated by Django 2.0.2 on 2018-02-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_mezzi', '0003_auto_20180220_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mezzo',
            name='ubicazione',
        ),
        migrations.AddField(
            model_name='mezzo',
            name='ubicazione',
            field=models.ForeignKey(default=1, on_delete=None, to='gest_mezzi.Impianto'),
            preserve_default=False,
        ),
    ]
