# Generated by Django 2.0.2 on 2018-02-20 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gest_mezzi', '0005_auto_20180220_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezzo',
            name='durata_noleggio',
            field=models.CharField(choices=[('1', '1 MESE'), ('2', '2 MESI'), ('3', '3 MESI'), ('4', '4 MESI'), ('5', '5 MESI')], default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
