# Generated by Django 2.0.2 on 2018-02-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_mezzi', '0008_auto_20180220_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezzo',
            name='proprieta',
            field=models.CharField(choices=[('NOLEGGIO', 'NL'), ('PROPRIETA CONSORZIO', 'PC'), ('PROPIETA FERLOG LOG FER', 'PL')], max_length=20),
        ),
    ]
