# Generated by Django 2.0.2 on 2018-02-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_mezzi', '0009_auto_20180220_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezzo',
            name='proprieta',
            field=models.CharField(choices=[('NOLEGGIO', 'NOL'), ('PROPRIETA CONSORZIO', 'CONS'), ('PROPIETA FERLOG LOG FER', 'LOG FER')], max_length=20),
        ),
    ]
