# Generated by Django 2.0.2 on 2018-02-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_mezzi', '0013_auto_20180220_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezzo',
            name='immagine',
            field=models.FileField(blank=True, upload_to='ferlog/uploads/images/'),
        ),
    ]
