# Generated by Django 2.0.2 on 2018-02-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_mezzi', '0015_auto_20180220_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mezzo',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='mezzi'),
        ),
    ]
