# Generated by Django 2.0.2 on 2018-02-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_mezzi', '0017_auto_20180220_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervento',
            fields=[
                ('idintervento', models.AutoField(primary_key=True, serialize=False)),
                ('data_richiesta', models.DateTimeField(auto_now_add=True)),
                ('richiesto_da', models.CharField(max_length=100, null=True)),
                ('dettagli', models.TextField(blank=True, max_length=500, null=True)),
                ('data_fermo', models.DateTimeField(blank=True, null=True)),
                ('data_fine_riparazione', models.DateTimeField(blank=True, null=True)),
                ('numero_giorni', models.CharField(max_length=5, null=True)),
                ('mezzo', models.ForeignKey(blank=True, on_delete=None, to='gest_mezzi.Mezzo')),
            ],
        ),
    ]
