# Generated by Django 2.0.2 on 2018-02-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gest_mezzi', '0018_intervento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervento',
            options={'verbose_name_plural': 'Interventi'},
        ),
    ]
