# Generated by Django 2.0.2 on 2018-02-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gest_mezzi', '0019_auto_20180220_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervento',
            old_name='data_richiesta',
            new_name='data_apertura',
        ),
        migrations.RenameField(
            model_name='intervento',
            old_name='data_fermo',
            new_name='fermo_dal',
        ),
    ]
