# Generated by Django 2.0.2 on 2018-02-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_mezzi', '0020_auto_20180220_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervento',
            name='costo_cliente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='intervento',
            name='costo_riparazione',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='intervento',
            name='fattura_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='gest_mezzi.Cliente'),
        ),
        migrations.AddField(
            model_name='intervento',
            name='preventivo_intervento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
